name: Tests

on:
  push:
    paths:
      - "/api/**"
      - "/tests/**"
  workflow_dispatch:

jobs:
  tests:
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Tests
        run: |
          pytest
          


