name: Tests

on:
  push:
    paths:
      - "/api/**"
      - "/tests/**"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          apt-get install -y pip &&\
          pip install --upgrade pip && pip install --upgrade -r /.docker/requirements.txt
      - name: Tests
        run: |
          pytest
          


